name: Periodically Generate warlords list

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab.

jobs:
  build:
    name: Build And Generate Warlords List
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # All history for all branches and tags.
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
          # Optional - x64 or x86 architecture, defaults to x64.
          architecture: x64
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.1.13
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Load cached venv
        id: cached-pip-wheels
        uses: actions/cache@v2
        with:
          path: ~/.cache
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
      - name: Install dependencies
        run: |
          poetry install --no-interaction --no-root
      - name: Install library
        run: |
          poetry install --no-interaction
      - name: Lint And Test
        run: |
          source $VENV
          python -m pre_commit install -t pre-commit
          python -m pre_commit install -t pre-push
          python -m pre_commit run --all-files --show-diff-on-failure --hook-stage commit
          python -m pre_commit run --all-files --show-diff-on-failure --hook-stage push
      - name: Generate Warlords List
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          mkdir -p current
          python -m warlords
          mv -f warlords.json current
      - name: Push Current Warlords List To Branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: current # The branch to push to.
          FOLDER: current # The folder with the data to push.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Automatically provided by Actions.
          MESSAGE: "Current: ({sha}) {msg}" # The commit message.
          SQUASH_HISTORY: true # All previous commits on the target branch will be discarded.
          SKIP_EMPTY_COMMITS: true # Commits will only be pushed if the contents of the target branch will be changed as a result.
