name: Generate warlords list every 15 minutes

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab.

jobs:
  build:
    name: Build And Generate Warlords List
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # All history for all branches and tags.
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
          # Optional - x64 or x86 architecture, defaults to x64.
          architecture: x64
      - name: Setup Virtual Environment
        id: cache-virtualenv
        uses: syphar/restore-virtualenv@v1
      - name: Restore Pip Cache
        uses: syphar/restore-pip-download-cache@v1
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'
      - name: Install Dependencies
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'
        shell: bash
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools wheel
          python -m pip install --upgrade -r requirements.txt
          python -m pip install --upgrade -r requirements-dev.txt
          python -m pre_commit install -t pre-commit
          python -m pre_commit install -t pre-push
      - name: Lint And Test
        shell: bash
        run: |
          python -m pre_commit run --all-files --show-diff-on-failure --hook-stage commit
          python -m pre_commit run --all-files --show-diff-on-failure --hook-stage push
      - name: Generate Warlords List
        shell: bash
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          mkdir -p current
          python warlords.py
          mv -f warlords.json current
      - name: Push Current Warlords List To Branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: current # The branch to push to.
          FOLDER: current # The folder with the data to push.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Automatically provided by Actions.
          MESSAGE: "Current: ({sha}) {msg}" # The commit message.
          SQUASH_HISTORY: true # All previous commits on the target branch will be discarded.
          SKIP_EMPTY_COMMITS: true # Commits will only be pushed if the contents of the target branch will be changed as a result.
